author: MDCollins
database: false
description: Staff can now punch in or punch out depending on what they need to do!
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.punchcard.PunchCard
name: PunchCard
startup: postworld
url: http://blockmovers.com/
version: '${version}'
depend: [Vault]
commands:
  punch:
    usage: /<command> (action)
    aliases: pcd
permissions:
  punchcard.admin:
    default: false
